project:
  type: website
  output-dir: docs

lang: es 

# Configuración global del sitio
website:
  title: "Leonardo Mena"
  description: "Economía aplicada y datos de la República Dominicana"
  site-url: "https://leo8221.github.io/leonardo-mena-blog/"
  google-analytics: "G-W3JC0G3RJ1"
  # favicon: images/favicon.ico # Descomenta cuando tengas la imagen

  # Barra de navegación
  navbar:
    background: "#ffffff"
    left:
      - href: index.qmd
        text: Inicio
      - text: Temas
        menu:
          - text: "La República habla de"
            href: republica-habla-de.qmd
          - text: "Fundamentos"
            href: fundamentos.qmd
          - text: "Mis predecesores"
            href: predecesores.qmd
          - text: "Mitos económicos"
            href: mitos-economicos.qmd
      - href: categorias.qmd
        text: Categorías
#      - href: investigacion.qmd # Agregué tu sección de Papers que hablamos antes
#        text: Investigación
      - href: archivo.qmd
        text: Archivo
    right:
      - text: "<span style='background-color:#c86448; color:white; padding:5px 10px; border-radius:4px; font-weight:bold;'>Suscríbete</span>"
        href: suscribete.qmd
        aria-label: "Suscribirse al boletín"

  # Configuración para compartir en redes
  open-graph: true
  twitter-card: true

  # Pie de página
  page-footer:
    left: |
      <p style="margin: 0;">© 2025 Leonardo Mena · Economía Aplicada</p>
    center: |
      <a href="about.html">Sobre mí</a> · 
      <a href="mailto:leonardomena824@gmail.com">Contacto</a>
    right: |
      <a href="https://x.com/leonardomena824" target="_blank"><i class="bi bi-twitter"></i></a> · 
      <a href="https://www.instagram.com/leonardomena824/" target="_blank"><i class="bi bi-instagram"></i></a> · 
      <a href="https://www.linkedin.com/in/leonardo-mena-3b140724a/" target="_blank"><i class="bi bi-linkedin"></i></a> ·
      <a href="https://github.com/Leo8221" target="_blank"><i class="bi bi-github"></i></a>

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true            
    toc-title: "En este artículo"
    smooth-scroll: true
    link-external-newwindow: true
    code-copy: true      
    highlight-style: github
    
    comments: 
      giscus:
        repo: Leo8221/leonardo-mena-blog
        category: General 
        mapping: title
        reactions-enabled: true
        
       
        theme: 
          light: noborder_light   
          dark: transparent_dark 
        input-position: top     
        language: es                
        loading: lazy

execute:
  freeze: auto