name: Actualizar Observatorio

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-blog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chequear codigo
        uses: actions/checkout@v4

      - name: Instalar Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
          use-public-rspm: true

      - name: Instalar dependencias de Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev

      - name: Instalar paquetes R
        run: |
          install.packages(c("tidyverse", "highcharter", "readxl", "lubridate", "httr", "janitor", "rmarkdown", "knitr", "DT", "htmltools", "writexl", "bslib", "bsicons"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Renderizar Proyecto
        run: quarto render

      - name: Guardar cambios
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add docs/ _freeze/
          git commit -m "Auto-update: $(date +'%Y-%m-%d')" || echo "Sin cambios hoy"
          git push